[phases.setup]
commands = [
  "echo 'Installing bash and webp tools...'",
  "apt-get update",
  "apt-get install -y bash",
  "apt-get install -y webp",
  "echo 'Verifying bash installation...'",
  "bash --version",
  "echo 'Bash installation completed'"
]

[phases.build]
commands = [
  "echo 'Installing dependencies...'",
  "npm ci",
  "echo 'Building project...'",
  "npm run build",
  "echo 'Build completed'"
]

[start]
command = "npm run start"