      {
        id: "49",
        name: "MARC ANTOINE BARROIS GANYMEDE EDP 100ML",
        description: "Luxury French fragrance with sophisticated and contemporary appeal, perfect for those who appreciate fine perfumery",
        price: "550.00",
        category: "unisex",
        brand: "MARC",
        volume: "100ml",
        rating: "5.0",
        imageUrl: "/perfumes/marc_antoine_barrois_b683_100m_7_1.webp",
        moodImageUrl: "/perfumes/marc_antoine_barrois_b683_100m_7_2.webp",
        images: JSON.stringify([
          "/perfumes/marc_antoine_barrois_b683_100m_7_1.webp",
          "/perfumes/marc_antoine_barrois_b683_100m_7_2.webp"
        ]),
        inStock: true,
        topNotes: null,
        middleNotes: null,
        baseNotes: null,
      },
      {
        id: "50",
        name: "MARC ANTOINE BARROIS B-683 100ML EDP",
        description: "Luxury French fragrance with sophisticated and contemporary appeal, perfect for those who appreciate fine perfumery",
        price: "500.00",
        category: "unisex",
        brand: "MARC",
        volume: "100ml",
        rating: "5.0",
        imageUrl: "/perfumes/marc_antoine_barrois_encelade__8_1.webp",
        moodImageUrl: "/perfumes/marc_antoine_barrois_encelade__8_2.webp",
        images: JSON.stringify([
          "/perfumes/marc_antoine_barrois_encelade__8_1.webp",
          "/perfumes/marc_antoine_barrois_encelade__8_2.webp"
        ]),
        inStock: true,
        topNotes: null,
        middleNotes: null,
        baseNotes: null,
      },
      {
        id: "51",
        name: "MARC ANTOINE BARROIS ENCELADE EDP 100ML",
        description: "Luxury French fragrance with sophisticated and contemporary appeal, perfect for those who appreciate fine perfumery",
        price: "550.00",
        category: "unisex",
        brand: "MARC",
        volume: "100ml",
        rating: "5.0",
        imageUrl: "/perfumes/marc_antoine_barrois_encelade__9_1.webp",
        moodImageUrl: "/perfumes/marc_antoine_barrois_encelade__9_2.webp",
        images: JSON.stringify([
          "/perfumes/marc_antoine_barrois_encelade__9_1.webp",
          "/perfumes/marc_antoine_barrois_encelade__9_2.webp"
        ]),
        inStock: true,
        topNotes: null,
        middleNotes: null,
        baseNotes: null,
      },
      {
        id: "52",
        name: "MARC ANTOINE BARROIS ENCELADE EDP 30ML",
        description: "Luxury French fragrance with sophisticated and contemporary appeal, perfect for those who appreciate fine perfumery",
        price: "275.00",
        category: "unisex",
        brand: "MARC",
        volume: "30ml",
        rating: "5.0",
        imageUrl: "/perfumes/marc_antoine_barrois_ganymede__10_1.webp",
        moodImageUrl: "/perfumes/marc_antoine_barrois_ganymede__10_2.webp",
        images: JSON.stringify([
          "/perfumes/marc_antoine_barrois_ganymede__10_1.webp",
          "/perfumes/marc_antoine_barrois_ganymede__10_2.webp"
        ]),
        inStock: true,
        topNotes: null,
        middleNotes: null,
        baseNotes: null,
      },
      {
        id: "53",
        name: "MARC ANTOINE BARROIS GANYMEDE EDP 30ML",
        description: "Luxury French fragrance with sophisticated and contemporary appeal, perfect for those who appreciate fine perfumery",
        price: "290.00",
        category: "unisex",
        brand: "MARC",
        volume: "30ml",
        rating: "5.0",
        imageUrl: "/perfumes/marc_antoine_barrios_tilia_100_11_1.webp",
        moodImageUrl: "/perfumes/marc_antoine_barrios_tilia_100_11_2.webp",
        images: JSON.stringify([
          "/perfumes/marc_antoine_barrios_tilia_100_11_1.webp",
          "/perfumes/marc_antoine_barrios_tilia_100_11_2.webp"
        ]),
        inStock: true,
        topNotes: null,
        middleNotes: null,
        baseNotes: null,
      },
      {
        id: "54",
        name: "MARC ANTOINE BARRIOS TILIA 100ML EDP",
        description: "Luxury French fragrance with sophisticated and contemporary appeal, perfect for those who appreciate fine perfumery",
        price: "550.00",
        category: "unisex",
        brand: "MARC",
        volume: "100ml",
        rating: "5.0",
        imageUrl: "/perfumes/marc_antoine_barrois_tilia_edp_12_1.webp",
        moodImageUrl: "/perfumes/marc_antoine_barrois_tilia_edp_12_2.webp",
        images: JSON.stringify([
          "/perfumes/marc_antoine_barrois_tilia_edp_12_1.webp",
          "/perfumes/marc_antoine_barrois_tilia_edp_12_2.webp"
        ]),
        inStock: true,
        topNotes: null,
        middleNotes: null,
        baseNotes: null,
      },
      {
        id: "55",
        name: "MARC ANTOINE BARROIS TILIA EDP 30ML",
        description: "Luxury French fragrance with sophisticated and contemporary appeal, perfect for those who appreciate fine perfumery",
        price: "275.00",
        category: "unisex",
        brand: "MARC",
        volume: "30ml",
        rating: "5.0",
        imageUrl: "/perfumes/marc_antoine_barrois_aldebaran_13_1.webp",
        moodImageUrl: "/perfumes/marc_antoine_barrois_aldebaran_13_2.webp",
        images: JSON.stringify([
          "/perfumes/marc_antoine_barrois_aldebaran_13_1.webp",
          "/perfumes/marc_antoine_barrois_aldebaran_13_2.webp"
        ]),
        inStock: true,
        topNotes: null,
        middleNotes: null,
        baseNotes: null,
      },
      {
        id: "56",
        name: "MARC ANTOINE BARROIS ALDEBARAN EDP 100 ML",
        description: "Luxury French fragrance with sophisticated and contemporary appeal, perfect for those who appreciate fine perfumery",
        price: "550.00",
        category: "unisex",
        brand: "MARC",
        volume: "100ml",
        rating: "5.0",
        imageUrl: "/perfumes/marc_antoine_barrois_aldebaran_14_1.webp",
        moodImageUrl: "/perfumes/marc_antoine_barrois_aldebaran_14_2.webp",
        images: JSON.stringify([
          "/perfumes/marc_antoine_barrois_aldebaran_14_1.webp",
          "/perfumes/marc_antoine_barrois_aldebaran_14_2.webp"
        ]),
        inStock: true,
        topNotes: null,
        middleNotes: null,
        baseNotes: null,
      },
      {
        id: "57",
        name: "MARC ANTOINE BARROIS ALDEBARAN EDP 30 ML",
        description: "Luxury French fragrance with sophisticated and contemporary appeal, perfect for those who appreciate fine perfumery",
        price: "275.00",
        category: "unisex",
        brand: "MARC",
        volume: "30ml",
        rating: "5.0",
        imageUrl: "/perfumes/diptyque_tam_dao_75_ml_edp_15_1.webp",
        moodImageUrl: "/perfumes/diptyque_tam_dao_75_ml_edp_15_2.webp",
        images: JSON.stringify([
          "/perfumes/diptyque_tam_dao_75_ml_edp_15_1.webp",
          "/perfumes/diptyque_tam_dao_75_ml_edp_15_2.webp"
        ]),
        inStock: true,
        topNotes: null,
        middleNotes: null,
        baseNotes: null,
      },