      {
        id: "100",
        name: "CHANEL ALLURE HOMME",
        description: "Luxury French fragrance with sophisticated and timeless appeal, perfect for those who appreciate fine perfumery. Eau de Toilette - a light and refreshing fragrance concentration perfect for daily wear.",
        price: "480.00",
        category: "men",
        brand: "CHANEL",
        volume: "150ml",
        rating: "4.8",
        imageUrl: "/perfumes/chanel_allure_homme_1.webp",
        moodImageUrl: "/perfumes/chanel_allure_homme_2.webp",
        images: JSON.stringify(["/perfumes/chanel_allure_homme_1.webp","/perfumes/chanel_allure_homme_2.webp"]),
        inStock: true,
        topNotes: null,
        middleNotes: null,
        baseNotes: null,
      },
      {
        id: "101",
        name: "CHANEL ALLURE HOMME EDITION BLANCHE",
        description: "Luxury French fragrance with sophisticated and timeless appeal, perfect for those who appreciate fine perfumery. Eau de Parfum - a rich and long-lasting fragrance concentration ideal for evening wear.",
        price: "515.00",
        category: "men",
        brand: "CHANEL",
        volume: "100ml",
        rating: "4.8",
        imageUrl: "/perfumes/chanel_allure_homme_edition_blanche_1.webp",
        moodImageUrl: "/perfumes/chanel_allure_homme_edition_blanche_2.webp",
        images: JSON.stringify(["/perfumes/chanel_allure_homme_edition_blanche_1.webp","/perfumes/chanel_allure_homme_edition_blanche_2.webp"]),
        inStock: true,
        topNotes: null,
        middleNotes: null,
        baseNotes: null,
      },
      {
        id: "102",
        name: "CHANEL ALLURE HOMME EDITION BLANCHE",
        description: "Luxury French fragrance with sophisticated and timeless appeal, perfect for those who appreciate fine perfumery. Eau de Parfum - a rich and long-lasting fragrance concentration ideal for evening wear.",
        price: "620.00",
        category: "men",
        brand: "CHANEL",
        volume: "150ml",
        rating: "4.9",
        imageUrl: "/perfumes/chanel_allure_homme_edition_blanche_1.webp",
        moodImageUrl: "/perfumes/chanel_allure_homme_edition_blanche_2.webp",
        images: JSON.stringify(["/perfumes/chanel_allure_homme_edition_blanche_1.webp","/perfumes/chanel_allure_homme_edition_blanche_2.webp"]),
        inStock: true,
        topNotes: null,
        middleNotes: null,
        baseNotes: null,
      },
      {
        id: "103",
        name: "CHANEL ALLURE HOMME EDITION BLANCHE",
        description: "Luxury French fragrance with sophisticated and timeless appeal, perfect for those who appreciate fine perfumery. Eau de Parfum - a rich and long-lasting fragrance concentration ideal for evening wear.",
        price: "350.00",
        category: "men",
        brand: "CHANEL",
        volume: "50ml",
        rating: "4.7",
        imageUrl: "/perfumes/chanel_allure_homme_edition_blanche_1.webp",
        moodImageUrl: "/perfumes/chanel_allure_homme_edition_blanche_2.webp",
        images: JSON.stringify(["/perfumes/chanel_allure_homme_edition_blanche_1.webp","/perfumes/chanel_allure_homme_edition_blanche_2.webp"]),
        inStock: true,
        topNotes: null,
        middleNotes: null,
        baseNotes: null,
      },
      {
        id: "104",
        name: "CHANEL ALLURE HOMME SPORT",
        description: "Luxury French fragrance with sophisticated and timeless appeal, perfect for those who appreciate fine perfumery. Eau de Toilette - a light and refreshing fragrance concentration perfect for daily wear.",
        price: "300.00",
        category: "men",
        brand: "CHANEL",
        volume: "50ml",
        rating: "4.7",
        imageUrl: "/perfumes/chanel_allure_homme_sport_1.webp",
        moodImageUrl: "/perfumes/chanel_allure_homme_sport_2.webp",
        images: JSON.stringify(["/perfumes/chanel_allure_homme_sport_1.webp","/perfumes/chanel_allure_homme_sport_2.webp"]),
        inStock: true,
        topNotes: null,
        middleNotes: null,
        baseNotes: null,
      },
      {
        id: "105",
        name: "CHANEL ALLURE HOMME SPORT",
        description: "Luxury French fragrance with sophisticated and timeless appeal, perfect for those who appreciate fine perfumery. Cologne - a fresh and light fragrance concentration perfect for casual wear.",
        price: "420.00",
        category: "men",
        brand: "CHANEL",
        volume: "100ml",
        rating: "4.8",
        imageUrl: "/perfumes/chanel_allure_homme_sport_1.webp",
        moodImageUrl: "/perfumes/chanel_allure_homme_sport_2.webp",
        images: JSON.stringify(["/perfumes/chanel_allure_homme_sport_1.webp","/perfumes/chanel_allure_homme_sport_2.webp"]),
        inStock: true,
        topNotes: null,
        middleNotes: null,
        baseNotes: null,
      },
      {
        id: "106",
        name: "CHANEL ALLURE HOMME SPORT",
        description: "Luxury French fragrance with sophisticated and timeless appeal, perfect for those who appreciate fine perfumery. Cologne - a fresh and light fragrance concentration perfect for casual wear.",
        price: "480.00",
        category: "men",
        brand: "CHANEL",
        volume: "150ml",
        rating: "4.8",
        imageUrl: "/perfumes/chanel_allure_homme_sport_1.webp",
        moodImageUrl: "/perfumes/chanel_allure_homme_sport_2.webp",
        images: JSON.stringify(["/perfumes/chanel_allure_homme_sport_1.webp","/perfumes/chanel_allure_homme_sport_2.webp"]),
        inStock: true,
        topNotes: null,
        middleNotes: null,
        baseNotes: null,
      },
      {
        id: "107",
        name: "CHANEL ALLURE HOMME SPORT",
        description: "Luxury French fragrance with sophisticated and timeless appeal, perfect for those who appreciate fine perfumery. Cologne - a fresh and light fragrance concentration perfect for casual wear.",
        price: "290.00",
        category: "men",
        brand: "CHANEL",
        volume: "50ml",
        rating: "4.7",
        imageUrl: "/perfumes/chanel_allure_homme_sport_1.webp",
        moodImageUrl: "/perfumes/chanel_allure_homme_sport_2.webp",
        images: JSON.stringify(["/perfumes/chanel_allure_homme_sport_1.webp","/perfumes/chanel_allure_homme_sport_2.webp"]),
        inStock: true,
        topNotes: null,
        middleNotes: null,
        baseNotes: null,
      },
      {
        id: "108",
        name: "CHANEL ALLURE HOMME SPORT EAU EXTREME",
        description: "Luxury French fragrance with sophisticated and timeless appeal, perfect for those who appreciate fine perfumery. Eau de Parfum - a rich and long-lasting fragrance concentration ideal for evening wear.",
        price: "490.00",
        category: "men",
        brand: "CHANEL",
        volume: "100ml",
        rating: "4.8",
        imageUrl: "/perfumes/chanel_allure_homme_sport_eau_extreme_1.webp",
        moodImageUrl: "/perfumes/chanel_allure_homme_sport_eau_extreme_2.webp",
        images: JSON.stringify(["/perfumes/chanel_allure_homme_sport_eau_extreme_1.webp","/perfumes/chanel_allure_homme_sport_eau_extreme_2.webp"]),
        inStock: true,
        topNotes: null,
        middleNotes: null,
        baseNotes: null,
      },
      {
        id: "109",
        name: "CHANEL ALLURE HOMME SPORT EAU EXTREME",
        description: "Luxury French fragrance with sophisticated and timeless appeal, perfect for those who appreciate fine perfumery. Eau de Parfum - a rich and long-lasting fragrance concentration ideal for evening wear.",
        price: "400.00",
        category: "men",
        brand: "CHANEL",
        volume: "20ml",
        rating: "4.7",
        imageUrl: "/perfumes/chanel_allure_homme_sport_eau_extreme_1.webp",
        moodImageUrl: "/perfumes/chanel_allure_homme_sport_eau_extreme_2.webp",
        images: JSON.stringify(["/perfumes/chanel_allure_homme_sport_eau_extreme_1.webp","/perfumes/chanel_allure_homme_sport_eau_extreme_2.webp"]),
        inStock: true,
        topNotes: null,
        middleNotes: null,
        baseNotes: null,
      },
      {
        id: "110",
        name: "CHANEL ALLURE HOMME SPORT EAU EXTREME",
        description: "Luxury French fragrance with sophisticated and timeless appeal, perfect for those who appreciate fine perfumery. Eau de Parfum - a rich and long-lasting fragrance concentration ideal for evening wear.",
        price: "355.00",
        category: "men",
        brand: "CHANEL",
        volume: "50ml",
        rating: "4.7",
        imageUrl: "/perfumes/chanel_allure_homme_sport_eau_extreme_1.webp",
        moodImageUrl: "/perfumes/chanel_allure_homme_sport_eau_extreme_2.webp",
        images: JSON.stringify(["/perfumes/chanel_allure_homme_sport_eau_extreme_1.webp","/perfumes/chanel_allure_homme_sport_eau_extreme_2.webp"]),
        inStock: true,
        topNotes: null,
        middleNotes: null,
        baseNotes: null,
      },